<a href="https://colab.research.google.com/github/areeshaasif070-ux/Pandas-Tasks/blob/main/Pandas_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name: Areesha Asif
# Roll Number:876834

In [ ]:
import pandas as pd
#Creating a DataFrame

data = {
    "Name" : ["Areesha" , "Asif" , "Noor"] ,
    "Age" : [15 , 45 , 23] ,
    "Marks" :[90 , 85 , 50]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0  Areesha   15     90
1     Asif   45     85
2     Noor   23     50

In [ ]:
#Reading a Dataset

df = pd.read_csv("/content/Mall_Customers.csv")
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [ ]:
#Viewing Data
print(df.head())

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
print(df.tail())

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [ ]:
#Shape and Basic Properties


print("Shape:" , df.shape)


print("Columns:" , df.columns)


print("Dtypes:" , df.dtypes)

Shape: (200, 5)
Columns: Index(['CustomerID', 'Genre', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')
Dtypes: CustomerID                 int64
Genre                     object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [ ]:
#DataFrame Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [ ]:
#Statistical Summary

print(df.describe())

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [ ]:
#Selecting Columns

print(df["Age"])

0      19
1      21
2      20
3      23
4      31
       ..
195    35
196    45
197    32
198    32
199    30
Name: Age, Length: 200, dtype: int64

In [ ]:
print(df[["Age", "Genre"]])

     Age   Genre
0     19    Male
1     21    Male
2     20  Female
3     23  Female
4     31  Female
..   ...     ...
195   35  Female
196   45  Female
197   32    Male
198   32    Male
199   30    Male

[200 rows x 2 columns]

In [ ]:
#Selecting Rows — loc and iloc

#loc

print(df.loc[0 , "Age" ])

19

In [ ]:
#iloc

print(df.iloc[1 , 3])

15

In [ ]:
#Filtering Data

#print(df[df["Age"] >= 30])

print(df[df["Annual Income (k$)"] >= 19])

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[192 rows x 5 columns]

In [ ]:
 #Adding a New Column

data = {
     "Name" : ["Sara" , "Ayesha" , "Ali"] ,
     "Age" : [21 , 18 , 15] ,
     "Marks" : [50 , 70 , 40]
 }
DF = (pd.DataFrame(data))
DF["City"] = ["Karachi", "Lahore", "Karachi"]
print(DF)

DF["Bonus Marks"] = DF["Marks"] +10
print(DF)

     Name  Age  Marks     City
0    Sara   21     50  Karachi
1  Ayesha   18     70   Lahore
2     Ali   15     40  Karachi
     Name  Age  Marks     City  Bonus Marks
0    Sara   21     50  Karachi           60
1  Ayesha   18     70   Lahore           80
2     Ali   15     40  Karachi           50

In [ ]:
#Updating Values

DF.loc[0, "Marks"] = 55
print(DF)

DF.loc [1 ,"Marks"] = 78
print(DF)

     Name  Marks     City  Bonus Marks
0    Sara     55  Karachi           60
1  Ayesha     78   Lahore           80
2     Ali     40  Karachi           50
     Name  Marks     City  Bonus Marks
0    Sara     55  Karachi           60
1  Ayesha     78   Lahore           80
2     Ali     40  Karachi           50

In [ ]:
#Deleting Rows and Columns
#Delete a Column
df = df.drop("Age" , axis=1)
df

#Delete a Row

df = df.drop(3)
df

     CustomerID   Genre  Annual Income (k$)  Spending Score (1-100)
0             1    Male                  15                      39
1             2    Male                  15                      81
2             3  Female                  16                       6
4             5  Female                  17                      40
5             6  Female                  17                      76
..          ...     ...                 ...                     ...
195         196  Female                 120                      79
196         197  Female                 126                      28
197         198    Male                 126                      74
198         199    Male                 137                      18
199         200    Male                 137                      83

[199 rows x 4 columns]

In [ ]:
#Handling Missing Values

print(df.isnull())
print(df.isnull().sum())

     CustomerID  Genre    Age  Annual Income (k$)  Spending Score (1-100)
0         False  False  False               False                   False
1         False  False  False               False                   False
2         False  False  False               False                   False
3         False  False  False               False                   False
4         False  False  False               False                   False
..          ...    ...    ...                 ...                     ...
195       False  False  False               False                   False
196       False  False  False               False                   False
197       False  False  False               False                   False
198       False  False  False               False                   False
199       False  False  False               False                   False

[200 rows x 5 columns]
CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [ ]:
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [80, None, 50]
    }
DF = pd.DataFrame(data)
#print(DF.dropna())
#print( DF["Marks"].fillna(0))
print( DF["Marks"].fillna(DF["Marks"].mean()))

0    80.0
1    65.0
2    50.0
Name: Marks, dtype: float64

In [ ]:
#Handling Duplicate Data

data = {
    "Name": ["Ali", "Sara", "Ali"],
    "Marks": [80, 90, 80]
}

df = pd.DataFrame(data)

#print(df.duplicated())
#print(df.duplicated().sum())
print(df.drop_duplicates())

   Name  Marks
0   Ali     80
1  Sara     90

In [ ]:
#Sorting Data

#print(df.sort_values("Annual Income (k$)", ascending=True))
print(df.sort_values("Annual Income (k$)", ascending=False))

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
199         200    Male   30                 137                      83
198         199    Male   32                 137                      18
197         198    Male   32                 126                      74
196         197  Female   45                 126                      28
195         196  Female   35                 120                      79
..          ...     ...  ...                 ...                     ...
5             6  Female   22                  17                      76
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81

[200 rows x 5 columns]

In [ ]:
#Aggregation and GroupBy

print(df["Age"].sum())
print(df["Age"].mean())
print(df["Age"].max())
print(df["Age"].min())
print(df["Age"].count())

7770
38.85
70
18
200

In [ ]:
#groupby()
result = df.groupby("Genre")["Spending Score (1-100)"].mean()
print(result)

Genre
Female    51.526786
Male      48.511364
Name: Spending Score (1-100), dtype: float64

In [ ]:
#Combining DataFrames
#concat()

df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Marks": [80, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Ayesha"],
    "Marks": [75, 85]
})

print(pd.concat([df1 , df2],ignore_index=True))

     Name  Marks
0     Ali     80
1    Sara     90
2   Ahmed     75
3  Ayesha     85

In [ ]:
#merge()
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [80, 90, 75]
})

print(pd.merge(students,marks,on="ID"))

   ID   Name  Marks
0   1    Ali     80
1   2   Sara     90
2   3  Ahmed     75

Student Practice Tasks

In [ ]:

#Task 1

data = {
    "Name" :["Ali" , "Sara" , "Ahmed" , "Ayesha" , "Zain"] ,
    "Marks" : [70 , 85 , 60 , 95 , 45]}


df = pd.DataFrame(data)
print(df)

print("Average" , df["Marks"].mean())
print("Maximum" , df["Marks"].max())
print("Minimum" , df["Marks"].min())
print("Count" , df["Marks"].count())

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
Average 71.0
Maximum 95
Minimum 45
Count 5

In [ ]:
#Task 2

data = {
    "Name" :["Ali" , "Sara" , "Ahmed" , "Ayesha" , "Zain"] ,
    "Marks" : [70 , 85 , 60 , 95 , 45]}
df = pd.DataFrame(data)
print(df)

Passed = df[df["Marks"] >= 50]
print(Passed)

Failed = df[df["Marks"] < 50]
print(Failed)

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
   Name  Marks
4  Zain     45

In [ ]:
#Task 3
data = {
    "Name" :["Ali" , "Sara" , "Ahmed" , "Ayesha" , "Zain"] ,
    "Marks" : [70 , 85 , 60 , 95 , 45]}
df = pd.DataFrame(data)
print(df)

df["City"] = ["Karachi", "Lahore", "Karachi", "Islamabad", "Multan"]

print(df)

print(df[df["City"] == "Karachi"])

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
4    Zain     45
     Name  Marks       City
0     Ali     70    Karachi
1    Sara     85     Lahore
2   Ahmed     60    Karachi
3  Ayesha     95  Islamabad
4    Zain     45     Multan
    Name  Marks     City
0    Ali     70  Karachi
2  Ahmed     60  Karachi

In [ ]:
#Task 4

data = {
    "Name":["Ali" , "Sara" , "Ahmed" , "Ayesha" , "Zain"],
    "Marks" : [70 , 85 , 60 , 95 , 45],
    "Courses" :["AI" , "Web" , "AI" ,"Web" , "AI"]
}

df = pd.DataFrame(data)
result = df.groupby("Courses")["Marks"].mean()
print(result)

Courses
AI     58.333333
Web    90.000000
Name: Marks, dtype: float64

In [ ]:
#Task 5

data = {
    "Name" : ["Ali" , "Sara" , "Ahmed" , "Ayesha" , "Zain"],
    "Marks" : [80 , None , 70 , None , 90 ]
  }
df = pd.DataFrame(data)
df.isnull().sum()
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df)

     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0